Updated Russian translation in /help/* files
colobot/colobot-data pull request #50
Opened 2020-10-01 11:46 UTC by rvasin

2021-01-19 14:33 UTC, probfaber requested changes
Needs some fixies of auto translated text.

2021-01-19 14:33 UTC, probfaber commented on help/generic/po/ru.po
> +msgstr "<code>allmission   </code>Все миссия разблокированы, работает также в главном меню"
needs plural: миссия->миссии

2021-12-01 11:32 UTC, X64E commented on help/bots/po/ru.po
> +msgstr "<button 195/> Ножной Строитель"
Шагающий

2021-12-01 11:33 UTC, X64E commented on help/bots/po/ru.po
> +msgstr "Муравьиный ползучий бот, оснащенный нейтронной пушкой."
Шагающий бот с нейтронной пушкой.

2021-12-04 08:43 UTC, MrSimbax requested changes
See other reviews. Also, there are merge conflicts now.

2021-12-06 14:42 UTC, X64E commented
Thanks to @rvasin for make translation to Russian. But but for some reason, the errors were not fixed.
For complete work maked in this request i open new request https://github.com/colobot/colobot-data/pull/66 with corrections in trnslation. If everyone is satisfied, this request can be closed.

2021-12-15 17:12 UTC, MrSimbax commented
Thanks!

2021-12-15 17:12 UTC, closed without merging