Use curl if wget is not available
colobot/colobot-data pull request #90
Opened 2024-01-03 00:10 UTC by sparr

Fall back on `curl` if `wget` is not available to download music files.

`curl -z FILENAME -O` is effectively similar to `wget -N` except that it prints three warnings if the file doesn't exist. I can't find a clean way to silence these warnings without also eliminating the download progress output.

2024-01-03 02:47 UTC, sparr commented
Sorry about the wrong branch target. I'll try to get that fixed.

2024-02-02 06:29 UTC, AndreiCherniaev commented
> Sorry about the wrong branch target. I'll try to get that fixed.

Any news?

2024-07-11 23:31 UTC, hexagonrecursion requested changes
[cmake appears to have its own built-in method of downloading files.](https://cmake.org/cmake/help/latest/command/file.html#download) We should probably use that instead of relying on an external program.
```
file(DOWNLOAD <url> <file>)
```

2024-09-15 19:55 UTC, tomaszkax86 commented
No longer necessary, wget was replaced with CMake's FILE(DOWNLOAD) in https://github.com/colobot/colobot-data/pull/118

2024-09-15 19:55 UTC, closed without merging